spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Schema?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Flzx3qcYsyhl9t
